kavita:
  baseUri: "https://kavita.ivanxiao.com" #or env:KOMF_KAVITA_BASE_URI
  apiKey: "0007cfc4-94ca-4131-b99d-a75a4a36f02a" #or env:KOMF_KAVITA_API_KEY
  eventListener:
    enabled: false # if disabled will not connect to kavita and won't pick up newly added entries
    libraries: [ ]  # listen to all events if empty
  notifications:
    libraries: [ ]  # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
  metadataUpdate:
    default:
      # Update modes is the way komf will update metadata.
      # If you're using anything other than API then your existing files might be modified with embedded metadata
      # can use multiple options at once. available options are API, COMIC_INFO
      # experimental OPF mode is available for epub books. This mode is using calibre system install to update metadata
      updateModes: [ API, COMIC_INFO ]
      aggregate: false # if enabled will search and aggregate metadata from all configured providers
      mergeTags: false # if true and aggregate is enabled will merge tags from all providers
      mergeGenres: false # if true and aggregate is enabled will merge genres from all providers
      bookCovers: true #update book thumbnails
      seriesCovers: true #update series thumbnails
      postProcessing:
        seriesTitle: true #update series title
        seriesTitleLanguage: "ja" # series title update language
        alternativeSeriesTitles: true # use other title types as alternative title option
        alternativeSeriesTitleLanguages: # alternative title language. Only first language is used. Use single value for consistency
          - "en"
        orderBooks: false # will order books using parsed volume or chapter number. works only with COMIC_INFO
        languageValue: "zh" # set default language for series. Must use BCP 47 format e.g. "en"
database:
  file: ./database.sqlite #database file location.
metadataProviders:
  malClientId: "448e4459e67299636b2e3d47a1e2959c" #required for mal provider. See https://myanimelist.net/forum/?topicid=1973077
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
      # roles mapping can be applied the same way to any other provider
      authorRoles: [ "WRITER" ] # roles that will be mapped to author role
      artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ] # roles that will be mapped to artist role
    mal:
      priority: 5
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
    nautiljon:
      priority: 30
      enabled: false
    aniList:
      priority: 1
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
      tagsScoreThreshold: 60 # tags with this score or higher will be included
      tagsSizeLimit: 15 # amount of tags that will be included
    yenPress:
      priority: 50
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
    kodansha:
      priority: 60
      enabled: false
    viz:
      priority: 70
      enabled: false
    bookWalker:
      priority: 80
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
    mangaDex:
      priority: 90
      enabled: false
server:
  port: 8085 #or env:KOMF_SERVER_PORT
logLevel: INFO #or env:KOMF_LOG_LEVEL
